remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

title: "Subham Das"
description: "Subham Das|MBA|Marketing & Finance"
logo: assets/Profile.jpg
email: subhamdaas03@gmail.com
linkedin: https://www.linkedin.com/in/subham-das-b113072b9
