remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

title: "Subham Das"
description: "MBA | Marketing & Finance  

email: subhamdaas03@gmail.com  

linkedin: https://www.linkedin.com/in/subham-das-b113072b9?utm_source=share_via&utm_content=profile&utm_medium=member_android"
logo: assets/Profile.jpg
 
 
