remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Subham Das]
description: [ Turning Data into insights]
logo: assets/https://github.com/subhamdaas03-Craft/Subham-portfolio-repo/blob/main/1000248554.jpg
